[libraries]
configurate-bom = "org.spongepowered:configurate-bom:4.1.2"
configurate-core = { module = "org.spongepowered:configurate-core" }
configurate-toml = "me.lucko.configurate:configurate-toml:4.1"
gson = "com.google.code.gson:gson:2.10.1"
